name: Documentation Tests

on:
  push:
    branches:
      - main
      - master
    paths:
      - 'README.md'
  pull_request:
    branches:
      - main
      - master
    paths:
      - 'README.md'

jobs:
  test-readme:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Install textlint and plugins
        run: |
          npm install textlint textlint-rule-common-misspellings textlint-rule-no-dead-link textlint-rule-terminology textlint-rule-write-good --save-dev

      - name: Configure textlint
        run: echo "rules:\n  terminology: true\n  common-misspellings: true\n  write-good:\n    adverb: false\n    passive: false\n    tooWordy: false\n    weasel: false\n  no-dead-link: true" > .documentation_test.yaml

      - name: Check spelling and grammar
        run: npx textlint README.md

      - name: Install markdown-link-check
        run: npm install -g markdown-link-check

      - name: Check links in the README
        run: markdown-link-check README.md

      - name: Install markdownlint-cli
        run: npm install -g markdownlint-cli

      - name: Lint Markdown files
        run: markdownlint README.md

      - name: Check readability
        run: npx textlint --rule write-good README.md
